In [2]:
#求矩阵的转置，矩阵的逆，矩阵的奇异值分解，计算线性方程[[2,8], [1,5]]*[[x],[y]]=[[9],[31]]

import numpy as np

b = np.arange(24).reshape(2,3,4) #改变数组形状

b.ravel() #将多维数组变成一维数组

b.flatten() # 与ravel()相同，但是flatten()返回的是真实的数组，需要分配新的内存空间，而ravel()仅仅是改变视图。

b.shape = (6,4) #改变数组形状

b.transpose() #转置



a = np.arange(9).reshape(3,3)

b = np.arange(9).reshape(3,3)

np.hstack((a,b))  # 水平叠加注意 这里是两层括号

np.vstack((a,b)) #垂直叠加

np.dstack((a,b)) #深度叠加

np.hsplit(a,3) # 横向拆分

np.vsplit(a,3) # 纵向拆分

c= np.arange(27).reshape(3,3,3)

np.dsplit(c,3)  #深度拆分

#计算线性方程[[2,8], [1,5]]*[[x],[y]]=[[9],[31]]
a=np.array([[2,8],[1,5]])
b=np.array([[9],[31]])
np.linalg.solve(a,b)
print(np.linalg.solve(a,b))

[[-101.5]
 [  26.5]]


In [1]:
#2、读取iris中的数据（可以在程序中直接设置），计算并输出每一列数字型数据的最大值、最小值和平均值

import numpy as np

iris = np.array([

[5.2,3.4,1.4,0.2],

[4.7,3.2,1.6,0.2],

[4.8,3.1,1.6,0.2],

[5.4,3.4,1.5,0.4],

[5.2,4.1,1.5,0.1],

[5.5,4.2,1.4,0.2],

[4.9,3.1,1.5,0.1],

[5.0,3.2,1.2,0.2],

[5.5,3.5,1.3,0.2],

[4.9,3.1,1.5,0.1],

[4.4,3.0,1.3,0.2],

[5.1,3.4,1.5,0.2],

[5.0,3.5,1.3,0.3],

[6.3,2.3,4.4,1.3],

[5.6,3.0,4.1,1.3],

[5.5,2.5,4.0,1.3],

[5.5,2.6,4.4,1.2],

[6.1,3.0,4.6,1.4],

[5.8,2.6,4.0,1.2],

[5.0,2.3,3.3,1.0],

[5.6,2.7,4.2,1.3],

[5.7,3.0,4.2,1.2],

[5.7,2.9,4.2,1.3],

[6.2,2.9,4.3,1.3],

[5.1,2.5,3.0,1.1],

[5.7,2.8,4.1,1.3],

[6.0,3.0,4.8,1.8],

[6.9,3.1,5.4,2.1],

[6.7,3.1,5.6,2.4],

[6.9,3.1,5.1,2.3],

[5.8,2.7,5.1,1.9],

[6.8,3.2,5.9,2.3],

[6.7,3.3,5.7,2.5],

[6.7,3.0,5.2,2.3],

[6.3,2.5,5.0,1.9],

[6.5,3.0,5.2,2.0],

[6.2,3.4,5.4,2.3],

[5.9,3.0,5.1,1.8]])

print(iris.max(axis=0)) #每一列的最大值

print(iris.min(axis=0)) #每一列的最小值

print(iris.mean(axis=0)) #每一列的平均值

[6.9 4.2 5.9 2.5]
[4.4 2.3 1.2 0.1]
[5.70526316 3.04473684 3.55       1.16842105]


In [3]:
import numpy as np

iris = np.array([

[5.2,3.4,1.4,0.2],

[4.7,3.2,1.6,0.2],

[4.8,3.1,1.6,0.2],

[5.4,3.4,1.5,0.4],

[5.2,4.1,1.5,0.1],

[5.5,4.2,1.4,0.2],

[4.9,3.1,1.5,0.1],

[5.0,3.2,1.2,0.2],

[5.5,3.5,1.3,0.2],

[4.9,3.1,1.5,0.1],

[4.4,3.0,1.3,0.2],

[5.1,3.4,1.5,0.2],

[5.0,3.5,1.3,0.3],

[6.3,2.3,4.4,1.3],

[5.6,3.0,4.1,1.3],

[5.5,2.5,4.0,1.3],

[5.5,2.6,4.4,1.2],

[6.1,3.0,4.6,1.4],

[5.8,2.6,4.0,1.2],

[5.0,2.3,3.3,1.0],

[5.6,2.7,4.2,1.3],

[5.7,3.0,4.2,1.2],

[5.7,2.9,4.2,1.3],

[6.2,2.9,4.3,1.3],

[5.1,2.5,3.0,1.1],

[5.7,2.8,4.1,1.3],

[6.0,3.0,4.8,1.8],

[6.9,3.1,5.4,2.1],

[6.7,3.1,5.6,2.4],

[6.9,3.1,5.1,2.3],

[5.8,2.7,5.1,1.9],

[6.8,3.2,5.9,2.3],

[6.7,3.3,5.7,2.5],

[6.7,3.0,5.2,2.3],

[6.3,2.5,5.0,1.9],

[6.5,3.0,5.2,2.0],

[6.2,3.4,5.4,2.3],

[5.9,3.0,5.1,1.8]])

#打乱iris数据，并输出
iris = np.random.permutation(iris)
print(iris)

[[5.7 2.9 4.2 1.3]
 [6.7 3.  5.2 2.3]
 [6.9 3.1 5.1 2.3]
 [6.2 3.4 5.4 2.3]
 [6.7 3.1 5.6 2.4]
 [5.8 2.6 4.  1.2]
 [5.5 2.5 4.  1.3]
 [5.6 2.7 4.2 1.3]
 [5.5 2.6 4.4 1.2]
 [5.8 2.7 5.1 1.9]
 [4.4 3.  1.3 0.2]
 [5.7 2.8 4.1 1.3]
 [5.2 3.4 1.4 0.2]
 [5.1 2.5 3.  1.1]
 [5.9 3.  5.1 1.8]
 [5.1 3.4 1.5 0.2]
 [6.3 2.3 4.4 1.3]
 [6.7 3.3 5.7 2.5]
 [5.5 4.2 1.4 0.2]
 [6.3 2.5 5.  1.9]
 [5.  3.5 1.3 0.3]
 [5.5 3.5 1.3 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 3.1 1.5 0.1]
 [6.2 2.9 4.3 1.3]
 [5.6 3.  4.1 1.3]
 [6.  3.  4.8 1.8]
 [5.  3.2 1.2 0.2]
 [6.1 3.  4.6 1.4]
 [5.2 4.1 1.5 0.1]
 [6.9 3.1 5.4 2.1]
 [5.4 3.4 1.5 0.4]
 [5.  2.3 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.7 3.2 1.6 0.2]
 [6.5 3.  5.2 2. ]
 [6.8 3.2 5.9 2.3]
 [5.7 3.  4.2 1.2]]


In [5]:
#1、编写irisFilter函数，根据输入参数筛选出iris数据中第i列大于num的值的样本
def irisFilter(num,i,input_data):
    return input_data[input_data[:,i]>num]
print(irisFilter(3.0,1,iris))

#2、编写uppercaseFilter函数，过滤出所有的大写字母
def uppercaseFilter(input_data):
    return input_data[np.char.isupper(input_data)]
print(uppercaseFilter(np.array(['A','b','C','d','E','f'])))

#inputLetter = ["O","a","A","p","b","I","C","K"]

[[6.9 3.1 5.1 2.3]
 [6.2 3.4 5.4 2.3]
 [6.7 3.1 5.6 2.4]
 [5.2 3.4 1.4 0.2]
 [5.1 3.4 1.5 0.2]
 [6.7 3.3 5.7 2.5]
 [5.5 4.2 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.5 3.5 1.3 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.2 4.1 1.5 0.1]
 [6.9 3.1 5.4 2.1]
 [5.4 3.4 1.5 0.4]
 [4.9 3.1 1.5 0.1]
 [4.7 3.2 1.6 0.2]
 [6.8 3.2 5.9 2.3]]
['A' 'C' 'E']
