In [10]:
import numpy as np
#利用函数升序排列 a=np.array([5,9,1,15,3,10])
def sort(a):
    for i in range(len(a)):
        for j in range(i+1,len(a)):
            if a[i]>a[j]:
                a[i],a[j]=a[j],a[i]
    return a
#按索引值创建有序排列 a=np.array([4,5,9,1,3])
def sort_index():
    a=np.array([4,5,9,1,3])
    b=np.argsort(a)
    print(b)
    print(a[b])
    print(a)
#按行分别排序a=np.array([[8,1,5,9],[5,4,9,6],[7,1,5,3]])
def sort_row():
    a=np.array([[8,1,5,9],[5,4,9,6],[7,1,5,3]])
    b=np.argsort(a,axis=1)
    print(b)
    print(a[b])
    print(a)
#按列分别排序a=np.array([[8,1,5,9],[5,4,9,6],[7,1,5,3]])
def sort_col():
    a=np.array([[8,1,5,9],[5,4,9,6],[7,1,5,3]])
    b=np.argsort(a,axis=0)
    print(b)
    print(a[b])
    print(a)
#按利用函数筛选值大于10的值 a=np.array([1,31,2,10,9,5,16,22,17])
def filter(a):
    for i in range(len(a)):
        if a[i]<=10:
            a[i]=0
    print(a)
def main():
    a=np.array([5,9,1,15,3,10])
    print(sort(a))
    sort_index()
    sort_row()
    sort_col()
    a=np.array([1,31,2,10,9,5,16,22,17])
    filter(a)
if __name__ == '__main__':
    main()

[ 1  3  5  9 10 15]
[3 4 0 1 2]
[1 3 4 5 9]
[4 5 9 1 3]
[[1 2 0 3]
 [1 0 3 2]
 [1 3 2 0]]


IndexError: index 3 is out of bounds for axis 0 with size 3

In [15]:
#读取文件iris.data内容转换为结构化数组并筛选出一类鸢尾花（可以提前指定），并按第一列排序输出
import numpy as np
#读取文件iris.data内容转换为结构化数组  
def read_file():
    a=np.loadtxt('Iris.data',delimiter=',',dtype='str')
    b=np.array(a)
    return b
#筛选出一类鸢尾花（可以提前指定），并按第一列排序输出
def filter_sort():
    a=read_file()
    b=a[a[:,4]=='Iris-setosa']
    c=np.argsort(b[:,0])
    print(b[c])
if __name__ == '__main__':
    filter_sort()

[['4.3' '3' '1.1' '0.1' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.4' '3' '1.3' '0.2' 'Iris-setosa']
 ['4.4' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.5' '2.3' '1.3' '0.3' 'Iris-setosa']
 ['4.6' '3.6' '1' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['4.6' '3.2' '1.4' '0.2' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.9' '0.2' 'Iris-setosa']
 ['4.8' '3.1' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3' '1.4' '0.1' 'Iris-setosa']
 ['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3' '1.4' '0.3' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['4.9' '3' '1.4' '0.2' 'Iris-setosa']
 ['5' '3.5' '1.3' '0.3' 'Iris-setosa']
 ['5' '3.2' '1.2' '0.2' 'Iris-setosa']
 ['5' '3.5' '1.6' '0.6' 'Iris-setosa']
 ['5' '3.4' '1.6' '0.4' 'Iris-setosa']
 ['5' '3' '1.6' '0.2' 'Iris-setosa']